In [1]:
from pathlib import Path
import json
from collections import defaultdict, Counter

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from IPython.display import display

## Sample100

In [2]:
dir_sample100 = Path('/projects/mtg/projects/sample-identification/datasets/sample100_withnoise')

path_csv_sample100_samples = dir_sample100 / 'meta' / 'samples.csv'
path_csv_sample100_tracks = dir_sample100 / 'meta' / 'tracks.csv'
path_csv_sample100_yt = dir_sample100 / 'meta' / 'youtube-links.csv'

In [3]:
df_sample100_samples = pd.read_csv(path_csv_sample100_samples, delimiter=',', encoding='latin-1')

with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(df_sample100_samples)

,sample_id,original_track_id,sample_track_id,t_original,t_sample,n_repetitions,sample_type,interpolation,comments
0,S001,T002,T001,0,0,19,riff,no,starts counted (sample ABCD looped ABCBCBCD)
1,S002,T003,T004,0,0,4,riff,no,intro
2,S003,T003,T004,34,53,3,riff,no,refrain with horns
3,S004,T005,T006,0,37,60,beat,no,
4,S005,T007,T008,53,0,10,riff,no,(very clean: same pitch and only layer)
5,S006,T010,T009,0,1,37,beat,no,probably samples both bars (with two decks?)
6,S007,T011,T012,1,0,85,riff,no,(sample a bit gated in the end)
7,S008,T014,T013,74,5,10,riff,maybe,beginning of riff counted (rest 'chopped')
8,S009,T015,T016,0,3,37,riff,yes,interpolation or other version
9,S010,T018,T017,0,0,1,riff,no,
10,S012,T021,T020,0,0,38,riff,maybe,time sampled unclear (0:00 or 2:25?)
11,S013,T023,T022,1,10,51,riff,maybe,piano
12,S014,T025,T024,0,21,37,riff,no,
13,S015,T027,T026,5,12,38,riff,no,
14,S016,T029,T028,0,37,50,riff,no,
15,S017,T031,T030,8,10,43,riff,no,first half of loop
16,S018,T033,T032,1,18,217,beat,probably not,(samples 2nd measure hence short and no melody)
17,S019,T035,T034,40,10,48,riff,no,(vocals)
18,S020,T033,T036,0,2,33,riff,no,
19,S021,T038,T037,0,0,50,riff,no,the guitar bar
20,S022,T043,T037,141,26,22,riff,maybe,
21,S023,T040,T039,0,2,21,riff,yes,interpolation
22,S024,T042,T041,0,4,40,riff,no,the guitar bar
23,S025,T045,T044,0,39,67,riff,no,very soft and hard to count
24,S027,T049,T048,0,9,25,riff,no,
25,S028,T050,T048,0,0,19,riff,no,half samples not counted (second halves)
26,S029,T052,T051,0,10,85,beat,no,only the measures with single BD counted
27,S030,T052,T039,0,13,76,beat,no,
28,S031,T052,T037,0,4,110,beat,maybe,BD filtered out or replay
29,S032,T052,T053,1,20,147,beat,maybe,HH filtered out or replay
30,S033,T045,T054,0,12,92,One note,no,
31,S035,T056,T057,3,6,44,riff,no,
32,S036,T058,T059,5,10,26,riff,maybe,Short sample Ð intro not counted
33,S037,T060,T061,63,63,3,riff,no,vocals only
34,S038,T062,T063,35,1,5,riff,no,refrain w/ vocals (long)
35,S039,T064,T065,25,22,157,riff,no,the flute verse
36,S040,T066,T067,7,18,34,riff,no,both instr/vocal instr parts chopped?
37,S041,T068,T069,6,13,23,riff,maybe,nice and long (11 seconds)
38,S042,T070,T071,0,0,38,riff,no,
39,S043,T072,T073,0,5,55,riff,no,piano part
40,S044,T074,T075,7,8,79,riff,no,Short alternates full/half sample
41,S045,T076,T077,32,0,143,riff,no,Only 8 note string riff counted
42,S046,T078,T079,4,2,151,One note,no,Less than one second
43,S047,T080,T081,3,20,15,riff,no,Only repetitions of string riff counted
44,S048,T082,T048,2,0,68,beat,no,
45,S049,T083,T054,321,12,80,beat,maybe,
46,S050,T085,T084,1,0,45,beat,probably,
47,S051,T116,T086,88,20,80,beat,no,
48,S052,T088,T086,1,179,3,beat,no,
49,S054,T090,T091,0,3,91,beat,no,
50,S055,T090,T092,0,0,101,beat,no,
51,S056,T094,T093,5,0,60,riff,no,
52,S057,T090,T093,0,0,150,beat,no,half of the samples used in S054 and S55
53,S058,T095,T093,138,0,40,riff,no,
54,S060,T098,T097,0,8,204,beat,no,pretty short but ok
55,S061,T098,T099,0,11,150,beat,no,Pretty short only full cycles counted
56,S062,T098,T100,0,5,100,beat,no,pretty short but ok
57,S063,T101,T102,1,0,24,riff,no,
58,S064,T104,T103,1,15,96,beat,no,
59,S067,T108,T109,6,54,114,beat,no,
60,S068,T111,T110,0,15,55,riff,no,
61,S069,T112,T110,14,0,1,riff,no,
62,S071,T116,T115,88,7,82,beat,no,
63,S072,T117,T115,1,60,7,riff,no,
64,S073,T119,T118,5,0,139,beat,no,
65,S074,T085,T121,1,0,74,beat,yes,Perhaps chopped with compression or gated reverb: different timbre; yet accurate pattern
66,S078,T145,T144,12,39,2,riff,no,
67,S079,T145,T146,1,0,22,beat,no,
68,S080,T148,T147,18,5,24,riff,no,
69,S081,T148,T149,18,13,15,riff,no,end of loop doubled (not counted)
70,S082,T151,T150,6,114,7,riff,no,
71,S083,T145,T152,3,56,28,beat,no,
72,S084,T154,T153,18,0,54,riff,no,LF only
73,S086,T154,T157,1,1,9,riff,no,intro
74,S089,T160,T157,0,64,8,riff,no,
75,S091,T162,T163,0,17,3,beat,probably,HF only and soft
76,S092,T162,T164,8,7,53,riff,no,
77,S094,T167,T166,6,15,43,riff,no,Bass + synth
78,S098,T173,T172,108,5,71,riff,no,
79,S101,T177,T176,0,0,27,riff,no,
80,S103,T180,T179,1,1,12,riff,no,
81,S104,T182,T181,0,0,99,riff,no,
82,S106,T185,T184,0,135,8,riff,no,
83,S107,T083,T184,321,137,7,beat,no,
84,S109,T160,T187,0,9,77,riff,no,might be 39
85,S112,T088,T187,1,0,21,beat,no,
86,S113,T083,T189,321,137,4,beat,no,might be 2
87,S114,T083,T190,321,0,102,beat,no,
88,S115,T083,T191,321,11,112,beat,no,
89,S116,T193,T192,106,5,75,beat,no,Beginnings counted
90,S120,T199,T184,5,2,71,riff,no,
91,S121,T064,T065,2,0,12,riff,no,the intro/refrain riff
92,S122,T072,T073,4,32,5,riff,no,brass part
93,S123,T062,T063,59,49,44,riff,no,verse (very soft)
94,S124,T052,T051,1,13,80,beat,no,only the measures with double BD counted
95,S125,T042,T041,7,12,16,riff,no,the guitar + strings bar
96,S126,T038,T037,4,52,10,riff,no,the guitar + brass bar
97,S127,T031,T030,46,13,43,riff,no,end of loop
98,S128,T029,T028,5,27,4,riff,no,10 sec refrain
99,S129,T023,T022,11,84,2,riff,maybe,saxophone
100,S130,T014,T013,68,0,1,riff,no,intro not interpolated
101,S131,T003,T004,23,20,9,riff,no,repeated beat (of which 3 included in S2)
102,S134,T167,T166,2,25,14,riff,no,Just bass
103,S135,T199,T184,14,58,3,riff,no,brass riff
104,S136,T199,T184,66,0,2,riff,no,brass crescendo
105,S137,T173,T172,1,44,14,riff,no,

In [4]:
sample100_dict_gt = {}
for _,row in df_sample100_samples.iterrows():
    sample100_dict_gt[row["sample_id"]] = {
        "src_audio_id": row["original_track_id"],
        "dst_audio_id": row["sample_track_id"],
    }

In [5]:
with open("sample100-ground-truth.json", "w") as out_f:
    json.dump(sample100_dict_gt, out_f)

In [4]:
df_sample100_tracks = pd.read_csv(path_csv_sample100_tracks, delimiter=',', skipinitialspace=True)

with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(df_sample100_tracks)

,track_id,artist,title,year,genre
0,T001,OC,Time's Up,1994,Hip-hop
1,T002,Les Demerle,A Day in the Life,1968,Jazz
2,T003,David Axelrod,Holy Thursday,1968,Jazz
3,T004,Lil Wayne,Dr. Carter,2008,Hip-hop
4,T005,Clyde McPhatter,Mixed Up Cup,1970,R&B/Soul
5,T006,Common,In My Own World (Check the Method),1994,Hip-hop
6,T007,Monty Alexander,Love and Happiness,1974,Jazz
7,T008,The Beatnuts,Let Off a Couple,1994,Hip-hop
8,T009,Beastie Boys,Rhymin & Stealin',1986,Hip-hop
9,T010,Led Zeppelin,When The Levee Breaks,1971,Rock
10,T011,Bill Withers,Grandma's Hands,1971,R&B/Soul
11,T012,Blackstreet,No Diggity,1996,Hip-hop
12,T013,Jay-Z,Roc Boys (and the Winner is),2007,Hip-hop
13,T014,Menahan Street Band,Make the Road by Walking,2006,World
14,T015,Lou Reed,Walk on the Wild Side,1971,Rock
15,T016,A Tribe Called Quest,Can I Kick it?,1990,Hip-hop
16,T017,House of Pain,Jump Around,1992,Hip-hop
17,T018,Bob & Earl,Harlem Shuffle,1963,R&B/Soul
18,T020,Will Smith,Miami,1997,Hip-hop
19,T021,The Whispers,And the Beat Goes On,1980,Disco
20,T022,Asheru ft. Talib Kweli,Mood Swing,2002,Hip-hop
21,T023,Duke Ellington and John Coltrane,In a Sentimental Mood,1963,Jazz
22,T024,Wu-Tang Clan,C.R.E.A.M.,1993,Hip-hop
23,T025,The Charmels,As Long as I've Got You,1967,R&B/Soul
24,T026,Beastie Boys,Rock Hard,1985,Hip-hop
25,T027,AC/DC,Back in Black,1980,Rock
26,T028,Wu-Tang Clan,Tearz,1993,Hip-hop
27,T029,Wendy Rene,After Laughter (Comes Tears),1964,R&B/Soul
28,T030,Non Phixion,Rock Stars,2002,Hip-hop
29,T031,Bar-Kays,In the hole,1969,R&B/Soul
30,T032,A Tribe Called Quest ft. Leaders of the New School & Kid Hood,Scenario (Remix),1992,Hip-hop
31,T033,The Emotions,Blind Alley,1972,R&B/Soul
32,T034,Pete Rock & C.L. Smooth,Straighten it Out,1992,Hip-hop
33,T035,Ernie Hines,Our Generation,1972,R&B/Soul
34,T036,Big Daddy Kane,Ain't No Half-Steppin',1988,Hip-hop
35,T037,De La Soul,Eye Know,1989,Hip-hop
36,T038,The Mad Lads,Make This Young Lady Mine,1969,R&B/Soul
37,T039,Biz Markie,Just a Friend,1989,Hip-hop
38,T040,Freddie Scott,You Got What I Need,1968,R&B/Soul
39,T041,Killah Priest ft. Hell Razah and Tekitha,One Step,1998,Hip-hop
40,T042,William Bell,I Forgot to Be Your Lover,1968,R&B/Soul
41,T043,Otis Redding,(Sittin' On) the Dock of the Bay,1968,R&B/Soul
42,T044,Wu-Tang Clan,Protect Ya Neck,1993,Hip-hop
43,T045,The J.B.'s,The Grunt,1970,R&B/Soul
44,T048,De La Soul,Change in Speak,1989,Hip-hop
45,T049,Cymande,Bra,1972,Funk
46,T050,The Mad Lads,No Strings Attached,1969,Hip-hop
47,T051,Nas,Memory Lane (Sittin' in Da Park),1994,Hip-hop
48,T052,Lee Dorsey,Get Out of My Life Woman,1966,R&B/Soul
49,T053,Fat Joe,Flow Joe,1993,Hip-hop
50,T054,Public Enemy,Rebel Without a Pause,1987,Hip-hop
51,T056,Blowfly,Outro,1973,Funk
52,T057,Jurassic 5,Quality Control,2000,Hip-hop
53,T058,David McCallum,The Edge,1967,Classical
54,T059,Dr. Dre ft. Snoop Dogg,The Next Episode,1999,Hip-hop
55,T060,Bobby Caldwell,Open Your Eyes,1980,Jazz
56,T061,Common,The Light,2000,Hip-hop
57,T062,Dido,Thank You,2000,Pop
58,T063,Eminem,Stan,2000,Hip-hop
59,T064,Eddie Holman,It's Over,1977,R&B/Soul
60,T065,Ghostface Killah & RZA,Nutmeg,2000,Hip-hop
61,T066,Foreigner,Cold as Ice,1977,Rock
62,T067,M.O.P.,Cold as Ice,2000,Hip-hop
63,T068,Grace Jones,Nightclubbing,1981,Disco
64,T069,Shyne & Barrington Levy,Bad Boyz,2000,Hip-hop
65,T070,Hossam Ramzy,Khusara Khusara,1994,World
66,T071,Jay-Z & UKG,Big Pimpin',1999,Hip-hop
67,T072,Jack Mayborn,Music People,1978,R&B/Soul
68,T073,Prodigy,Keep it Thoro,2000,Hip-hop
69,T074,Jimmie & Vella Cameron,Hey Boy Over There,1968,R&B/Soul
70,T075,Capone N' Noreaga,Invincible,2004,Hip-hop
71,T076,Raymond Lefevre & His Orchestra,The Days of Pearly Spencer,1967,R&B/Soul
72,T077,Black Rob,Whoa!,2000,Hip-hop
73,T078,Sam & Dave,Soul Sister Brown Sugar,1969,R&B/Soul
74,T079,M.O.P.,Ante Up,2000,Hip-hop
75,T080,Solomon Burke,Cool Breeze,1972,R&B/Soul
76,T081,Ghostface Killah & Raekwon,Apollo Kids,2000,Hip-hop
77,T082,The Monkeys,Mary Mary,1966,Rock
78,T083,James Brown,Funky Drummer,1970,Funk
79,T084,Jay-Z ft. Alicia Keys,Empire State of Mind,2009,Hip-hop
80,T085,Isaac Hayes,The Breakthrough,1974,R&B/Soul
81,T086,NWA,Straight outta Compton,1988,Hip-hop
82,T088,Funkadelic,You'll like it too,1981,Funk
83,T090,The Honey Drippers,Impeach The President,1973,R&B/Soul
84,T091,Nice & Smooth,Funky For You,1989,Hip-hop
85,T092,LL Cool J,Around the Way Girl,1990,Hip-hop
86,T093,Kris Kross,Jump,1992,Hip-hop
87,T094,Jackson 5,I want you back,1969,R&B/Soul
88,T095,Ohio Players,Funky Worm,1972,R&B/Soul
89,T097,Naughty by Nature,Hip Hop Hurray,1993,Hip-hop
90,T098,Five Stairsteps,Don't Change Your Love,1968,R&B/Soul
91,T099,A Tribe Called Quest,Jazz (We've Got),1991,Hip-hop
92,T100,Ice Cube,A Bird in the Hand,1991,Hip-hop
93,T101,Southside Movement,I been watchin' you,1973,Funk
94,T102,Cormega,American Beauty,2001,Hip-hop
95,T103,The Avalanches,Since I left you,2000,Hip-hop
96,T104,Lamont Dozier,Take off your make up,1973,R&B/Soul
97,T108,Gary Numan,Films,1979,Rock
98,T109,DJ Qbert,Eight,1994,Hip-hop
99,T110,Ghostface Killah & RZA,The Grain,2000,Hip-hop
100,T111,Rufus Thomas,Do the Funky Penguin,1971,R&B/Soul
101,T112,Rufus Thomas,The Breakdown (part 2),1971,R&B/Soul
102,T115,Salt-N-pepa,I desire,1986,Hip-hop
103,T116,The Winstons,Amen Brother,1969,R&B/Soul
104,T117,7th Wonder,Daisy Lady,1979,R&B/Soul
105,T118,Kanye West ft. Nas,Really Doe We Major,2005,Hip-hop
106,T119,Orange Krush,Action,1982,Funk
107,T121,LL Cool J,Breakthrough,1987,Hip-hop
108,T144,Beastie Boys,Time to get Ill,1986,Hip-hop
109,T145,Barry White,I'm gonna love you just a little more baby,1973,R&B/Soul
110,T146,De La Soul,De la Orgee,1989,Hip-hop
111,T147,Ras Kass,Rasassination,1998,Hip-hop
112,T148,Johnny Pate,Shaft in Africa,1973,R&B/Soul
113,T149,Jay-Z,Show me what you got,2006,Hip-hop
114,T150,Cypress Hill,Real Estate,1991,Hip-hop
115,T151,All The People,Cramp Your Style,1972,R&B/Soul
116,T152,Nas,One Mic,2001,Hip-hop
117,T153,Public Enemy,911 is a Joke,1990,Hip-hop
118,T154,Sound Experience,Devil with the bust,1974,R&B/Soul
119,T157,Geto Boys,Fuck a War,1991,Hip-hop
120,T160,Bobby Byrd,I Know You Got Soul,1971,R&B/Soul
121,T162,Joe Tex,Papa Was Too,1966,R&B/Soul
122,T163,Wu-Tang Clan,Wu-Tang Clan ain't nuthin ta F' wit,1993,Hip-hop
123,T164,EPMD,Jane,1988,Hip-hop
124,T166,Nikki D,Lettin' Off Steam,1990,Hip-hop
125,T167,The Politicians,Free Your Mind,1972,R&B/Soul
126,T172,3rd Bass,Oval Office,1989,Hip-hop
127,T173,Joe Quarterman & Free Soul,I'm gonna get you,1974,R&B/Soul
128,T176,Beastie Boys,Egg man,1989,Hip-hop
129,T177,Curtis Mayfield,Superfly,1972,R&B/Soul
130,T178,Crucial conflict,Showdown,1996,Hip-hop
131,T179,Beastie Boys,Brass Monkey,1986,Hip-hop
132,T180,Wild Sugar,Bring it Here,1981,Disco
133,T181,The Notorious B.I.G.,Respect,1994,Hip-hop
134,T182,KC & The Sunshine Band,I Get Lifted,1975,R&B/Soul
135,T184,Nas,Get Down,2002,Hip-hop
136,T185,The Blackbyrds,Rock Creek Park,1975,R&B/Soul
137,T187,Erik B. & Rakim,I Know You Got Soul,1987,Hip-hop
138,T189,NWA,Fuck the Police,1988,Hip-hop
139,T190,Erik B. & Rakim,Lyrics of Fury,1988,Hip-hop
140,T191,LL Cool J,Mama said knock you out,1990,Hip-hop
141,T192,Public Enemy,Welcome to the Terrordome,1989,Hip-hop
142,T193,Dyke & The Blazers,Let a woman be a woman let a man be a man,1969,Funk
143,T199,James Brown,The Boss,1973,R&B/Soul

In [5]:
# This is not the official file
df_sample100_yt = pd.read_csv(path_csv_sample100_yt, delimiter=',', skipinitialspace=True, header=None)
display(df_sample100_yt)

        0                                            1
0    T001  https://www.youtube.com/watch?v=dcsPoM2MalY
1    T002  https://www.youtube.com/watch?v=DkQFAxSwwjk
2    T003  https://www.youtube.com/watch?v=8j8pSu3U7WM
3    T004  https://www.youtube.com/watch?v=es6goNuH0lY
4    T005  https://www.youtube.com/watch?v=3ofnKqgTdSk
..    ...                                          ...
139  T190  https://www.youtube.com/watch?v=sulaqzO0ICk
140  T191  https://www.youtube.com/watch?v=vimZj8HW0Kg
141  T192  https://www.youtube.com/watch?v=e4Zey7o04Qk
142  T193  https://www.youtube.com/watch?v=E9DTQn6sxGA
143  T199  https://www.youtube.com/watch?v=jC2ZY2loo74

[144 rows x 2 columns]

In [13]:
df_sample100_original_yt = pd.read_csv('../tmp/Sample100.tsv', sep='\t')
df_sample100_original_yt

,Sample_id,whosampled_url,destination_url,source_url
0,S001,https://www.whosampled.com/sample/2238/O.C.-Ti...,https://www.youtube.com/watch?v=6gNmCGQRpcc,https://www.youtube.com/watch?v=DkQFAxSwwjk
1,S002,https://www.whosampled.com/sample/991/Lil-Wayn...,https://www.youtube.com/watch?v=WxPnAErnJ9A,https://www.youtube.com/watch?v=8j8pSu3U7WM
2,S004,https://www.whosampled.com/sample/20324/Common...,https://www.youtube.com/watch?v=_0aP1wjOt7E,https://www.youtube.com/watch?v=3ofnKqgTdSk
3,S005,https://www.whosampled.com/sample/3514/The-Bea...,https://www.youtube.com/watch?v=GX4hoAof2wQ,https://www.youtube.com/watch?v=YqAQiQ63r0A
4,S006,https://www.whosampled.com/sample/1340/Beastie...,https://www.youtube.com/watch?v=Xdutu8sWmbQ,https://www.youtube.com/watch?v=b97hqSDRspw
...,...,...,...,...
94,S131,https://www.whosampled.com/sample/991/Lil-Wayn...,https://www.youtube.com/watch?v=WxPnAErnJ9A,https://www.youtube.com/watch?v=8j8pSu3U7WM
95,S134,https://www.whosampled.com/sample/29796/Nikki-...,https://www.youtube.com/watch?v=VKMZCU6RJE4,https://www.youtube.com/watch?v=lqcX9TPWeNg
96,S135,https://www.whosampled.com/sample/781/Nas-Get-...,https://www.youtube.com/watch?v=IFQfQD2c47g,https://www.youtube.com/watch?v=KRAp5iIL3IA
97,S136,https://www.whosampled.com/sample/781/Nas-Get-...,https://www.youtube.com/watch?v=IFQfQD2c47g,https://www.youtube.com/watch?v=KRAp5iIL3IA
98,S137,https://www.whosampled.com/sample/96545/3rd-Ba...,https://www.youtube.com/watch?v=-YOuXDG6EHE,https://www.youtube.com/watch?v=0w7Ccje1jho

In [17]:
sample100_original_yt_ids = set(
    df_sample100_original_yt[["destination_url", "source_url"]]
    .map(extract_yt_id)
    .stack()
    .dropna()
)
print(len(sample100_original_yt_ids))

136

In [12]:
sample100_yt_ids = set(df_sample100_yt[1].apply(lambda x: x.split('watch?v=')[1]).to_list())
print(len(sample100_yt_ids))

144

In [19]:
print(len(sample100_original_yt_ids.intersection(sample100_yt_ids)))
print(len(sample100_original_yt_ids.difference(sample100_yt_ids)))
print(len(sample100_yt_ids.difference(sample100_original_yt_ids)))

48
88
96

## Build a whosampled dict

In [14]:
track_dict = {}
for _,row in df_sample100_tracks.iterrows():
    track_dict[row.track_id] = {"artist": row.artist, "title": row.title}

In [27]:
whosampled_dict = {}
for _, x in df_sample100_samples.iterrows():
#     whosampled_dict[x.sample_id]
    dct = {
        "original_track_artist": track_dict[x.original_track_id]["artist"],
        "original_track_title": track_dict[x.original_track_id]["title"],
        "sample_track_artist": track_dict[x.sample_track_id]["artist"],
        "sample_track_title": track_dict[x.sample_track_id]["title"],
    }
    orig  = f"{dct['original_track_artist']} - {dct['original_track_title']}"
    samp  = f"{dct['sample_track_artist']} - {dct['sample_track_title']}"
    print(f"{x.sample_id:>3}  |  {samp:<50}  →  {orig}")

S001  |  OC - Time's Up                                      →  Les Demerle - A Day in the Life
S002  |  Lil Wayne - Dr. Carter                              →  David Axelrod - Holy Thursday
S003  |  Lil Wayne - Dr. Carter                              →  David Axelrod - Holy Thursday
S004  |  Common - In My Own World (Check the Method)         →  Clyde McPhatter - Mixed Up Cup
S005  |  The Beatnuts - Let Off a Couple                     →  Monty Alexander - Love and Happiness
S006  |  Beastie Boys - Rhymin & Stealin'                    →  Led Zeppelin - When The Levee Breaks
S007  |  Blackstreet - No Diggity                            →  Bill Withers - Grandma's Hands
S008  |  Jay-Z - Roc Boys (and the Winner is)                →  Menahan Street Band - Make the Road by Walking
S009  |  A Tribe Called Quest - Can I Kick it?               →  Lou Reed - Walk on the Wild Side
S010  |  House of Pain - Jump Around                         →  Bob & Earl - Harlem Shuffle
S012  |  Will Smith - Miami                                  →  The Whispers - And the Beat Goes On
S013  |  Asheru ft. Talib Kweli - Mood Swing                 →  Duke Ellington and John Coltrane - In a Sentimental Mood
S014  |  Wu-Tang Clan - C.R.E.A.M.                           →  The Charmels - As Long as I've Got You
S015  |  Beastie Boys - Rock Hard                            →  AC/DC - Back in Black
S016  |  Wu-Tang Clan - Tearz                                →  Wendy Rene - After Laughter (Comes Tears)
S017  |  Non Phixion - Rock Stars                            →  Bar-Kays - In the hole
S018  |  A Tribe Called Quest ft. Leaders of the New School & Kid Hood - Scenario (Remix)  →  The Emotions - Blind Alley
S019  |  Pete Rock & C.L. Smooth - Straighten it Out         →  Ernie Hines - Our Generation
S020  |  Big Daddy Kane - Ain't No Half-Steppin'             →  The Emotions - Blind Alley
S021  |  De La Soul - Eye Know                               →  The Mad Lads - Make This Young Lady Mine
S022  |  De La Soul - Eye Know                               →  Otis Redding - (Sittin' On) the Dock of the Bay
S023  |  Biz Markie - Just a Friend                          →  Freddie Scott - You Got What I Need
S024  |  Killah Priest ft. Hell Razah and Tekitha - One Step  →  William Bell - I Forgot to Be Your Lover
S025  |  Wu-Tang Clan - Protect Ya Neck                      →  The J.B.'s - The Grunt
S027  |  De La Soul - Change in Speak                        →  Cymande - Bra
S028  |  De La Soul - Change in Speak                        →  The Mad Lads - No Strings Attached
S029  |  Nas - Memory Lane (Sittin' in Da Park)              →  Lee Dorsey - Get Out of My Life Woman
S030  |  Biz Markie - Just a Friend                          →  Lee Dorsey - Get Out of My Life Woman
S031  |  De La Soul - Eye Know                               →  Lee Dorsey - Get Out of My Life Woman
S032  |  Fat Joe - Flow Joe                                  →  Lee Dorsey - Get Out of My Life Woman
S033  |  Public Enemy - Rebel Without a Pause                →  The J.B.'s - The Grunt
S035  |  Jurassic 5 - Quality Control                        →  Blowfly - Outro
S036  |  Dr. Dre ft. Snoop Dogg - The Next Episode           →  David McCallum - The Edge
S037  |  Common - The Light                                  →  Bobby Caldwell - Open Your Eyes
S038  |  Eminem - Stan                                       →  Dido - Thank You
S039  |  Ghostface Killah & RZA - Nutmeg                     →  Eddie Holman - It's Over
S040  |  M.O.P. - Cold as Ice                                →  Foreigner - Cold as Ice
S041  |  Shyne & Barrington Levy - Bad Boyz                  →  Grace Jones - Nightclubbing
S042  |  Jay-Z & UKG - Big Pimpin'                           →  Hossam Ramzy - Khusara Khusara
S043  |  Prodigy - Keep it Thoro                             →  Jack Mayborn - Music People
S044  |  Capone N' Noreaga - Invincible                      →  Jimmie & Vella Cameron - Hey Boy Over There
S045  |  Black Rob - Whoa!                                   →  Raymond Lefevre & His Orchestra - The Days of Pearly Spencer
S046  |  M.O.P. - Ante Up                                    →  Sam & Dave - Soul Sister Brown Sugar
S047  |  Ghostface Killah & Raekwon - Apollo Kids            →  Solomon Burke - Cool Breeze
S048  |  De La Soul - Change in Speak                        →  The Monkeys - Mary Mary
S049  |  Public Enemy - Rebel Without a Pause                →  James Brown - Funky Drummer
S050  |  Jay-Z ft. Alicia Keys - Empire State of Mind        →  Isaac Hayes - The Breakthrough
S051  |  NWA - Straight outta Compton                        →  The Winstons - Amen Brother
S052  |  NWA - Straight outta Compton                        →  Funkadelic - You'll like it too
S054  |  Nice & Smooth - Funky For You                       →  The Honey Drippers - Impeach The President
S055  |  LL Cool J - Around the Way Girl                     →  The Honey Drippers - Impeach The President
S056  |  Kris Kross - Jump                                   →  Jackson 5 - I want you back
S057  |  Kris Kross - Jump                                   →  The Honey Drippers - Impeach The President
S058  |  Kris Kross - Jump                                   →  Ohio Players - Funky Worm
S060  |  Naughty by Nature - Hip Hop Hurray                  →  Five Stairsteps - Don't Change Your Love
S061  |  A Tribe Called Quest - Jazz (We've Got)             →  Five Stairsteps - Don't Change Your Love
S062  |  Ice Cube - A Bird in the Hand                       →  Five Stairsteps - Don't Change Your Love
S063  |  Cormega - American Beauty                           →  Southside Movement - I been watchin' you
S064  |  The Avalanches - Since I left you                   →  Lamont Dozier - Take off your make up
S067  |  DJ Qbert - Eight                                    →  Gary Numan - Films
S068  |  Ghostface Killah & RZA - The Grain                  →  Rufus Thomas - Do the Funky Penguin
S069  |  Ghostface Killah & RZA - The Grain                  →  Rufus Thomas - The Breakdown (part 2)
S071  |  Salt-N-pepa - I desire                              →  The Winstons - Amen Brother
S072  |  Salt-N-pepa - I desire                              →  7th Wonder - Daisy Lady
S073  |  Kanye West ft. Nas - Really Doe We Major            →  Orange Krush - Action
S074  |  LL Cool J - Breakthrough                            →  Isaac Hayes - The Breakthrough
S078  |  Beastie Boys - Time to get Ill                      →  Barry White - I'm gonna love you just a little more baby
S079  |  De La Soul - De la Orgee                            →  Barry White - I'm gonna love you just a little more baby
S080  |  Ras Kass - Rasassination                            →  Johnny Pate - Shaft in Africa
S081  |  Jay-Z - Show me what you got                        →  Johnny Pate - Shaft in Africa
S082  |  Cypress Hill - Real Estate                          →  All The People - Cramp Your Style
S083  |  Nas - One Mic                                       →  Barry White - I'm gonna love you just a little more baby
S084  |  Public Enemy - 911 is a Joke                        →  Sound Experience - Devil with the bust
S086  |  Geto Boys - Fuck a War                              →  Sound Experience - Devil with the bust
S089  |  Geto Boys - Fuck a War                              →  Bobby Byrd - I Know You Got Soul
S091  |  Wu-Tang Clan - Wu-Tang Clan ain't nuthin ta F' wit  →  Joe Tex - Papa Was Too
S092  |  EPMD - Jane                                         →  Joe Tex - Papa Was Too
S094  |  Nikki D - Lettin' Off Steam                         →  The Politicians - Free Your Mind
S098  |  3rd Bass - Oval Office                              →  Joe Quarterman & Free Soul - I'm gonna get you
S101  |  Beastie Boys - Egg man                              →  Curtis Mayfield - Superfly
S103  |  Beastie Boys - Brass Monkey                         →  Wild Sugar - Bring it Here
S104  |  The Notorious B.I.G. - Respect                      →  KC & The Sunshine Band - I Get Lifted
S106  |  Nas - Get Down                                      →  The Blackbyrds - Rock Creek Park
S107  |  Nas - Get Down                                      →  James Brown - Funky Drummer
S109  |  Erik B. & Rakim - I Know You Got Soul               →  Bobby Byrd - I Know You Got Soul
S112  |  Erik B. & Rakim - I Know You Got Soul               →  Funkadelic - You'll like it too
S113  |  NWA - Fuck the Police                               →  James Brown - Funky Drummer
S114  |  Erik B. & Rakim - Lyrics of Fury                    →  James Brown - Funky Drummer
S115  |  LL Cool J - Mama said knock you out                 →  James Brown - Funky Drummer
S116  |  Public Enemy - Welcome to the Terrordome            →  Dyke & The Blazers - Let a woman be a woman let a man be a man
S120  |  Nas - Get Down                                      →  James Brown - The Boss
S121  |  Ghostface Killah & RZA - Nutmeg                     →  Eddie Holman - It's Over
S122  |  Prodigy - Keep it Thoro                             →  Jack Mayborn - Music People
S123  |  Eminem - Stan                                       →  Dido - Thank You
S124  |  Nas - Memory Lane (Sittin' in Da Park)              →  Lee Dorsey - Get Out of My Life Woman
S125  |  Killah Priest ft. Hell Razah and Tekitha - One Step  →  William Bell - I Forgot to Be Your Lover
S126  |  De La Soul - Eye Know                               →  The Mad Lads - Make This Young Lady Mine
S127  |  Non Phixion - Rock Stars                            →  Bar-Kays - In the hole
S128  |  Wu-Tang Clan - Tearz                                →  Wendy Rene - After Laughter (Comes Tears)
S129  |  Asheru ft. Talib Kweli - Mood Swing                 →  Duke Ellington and John Coltrane - In a Sentimental Mood
S130  |  Jay-Z - Roc Boys (and the Winner is)                →  Menahan Street Band - Make the Road by Walking
S131  |  Lil Wayne - Dr. Carter                              →  David Axelrod - Holy Thursday
S134  |  Nikki D - Lettin' Off Steam                         →  The Politicians - Free Your Mind
S135  |  Nas - Get Down                                      →  James Brown - The Boss
S136  |  Nas - Get Down                                      →  James Brown - The Boss
S137  |  3rd Bass - Oval Office                              →  Joe Quarterman & Free Soul - I'm gonna get you

In [36]:
sample_whosampled_dict = {}
with open("../tmp/sample100-whosampled.csv") as f:
    reader = csv.reader(f, delimiter=',')
    next(reader)
    for row in reader:
        if row[1]:
            sample_whosampled_dict[row[0]] = row[1]

In [37]:
sample_whosampled_dict

{'S001': '2238',
 'S002': '991',
 'S004': '20324',
 'S005': '3514',
 'S006': '1340',
 'S007': '23',
 'S008': '521',
 'S009': '120',
 'S010': '622',
 'S012': '47',
 'S013': '14037',
 'S014': '1158',
 'S015': '4692',
 'S016': '1164',
 'S017': '6394',
 'S018': '22803',
 'S019': '1764',
 'S020': '1384',
 'S021': '12020',
 'S022': '189',
 'S023': '2064',
 'S024': '4196',
 'S025': '4657',
 'S027': '14255',
 'S028': '14254',
 'S030': '11607',
 'S031': '35245',
 'S032': '11610',
 'S033': '804',
 'S035': '4125',
 'S036': '266',
 'S037': '666',
 'S038': '104',
 'S039': '8327',
 'S040': '153',
 'S041': '3147',
 'S042': '237',
 'S043': '17600',
 'S044': '17182',
 'S046': '249',
 'S047': '10934',
 'S048': '35246',
 'S049': '889',
 'S051': '806',
 'S052': '2291',
 'S054': '12802',
 'S055': '3410',
 'S056': '926',
 'S057': '56949',
 'S060': '6501',
 'S061': '6910',
 'S062': '9640',
 'S063': '2667',
 'S064': '9537',
 'S067': '74883',
 'S068': '13166',
 'S069': '31178',
 'S071': '21298',
 'S072': '21299',
 'S073': '4380',
 'S078': '14313',
 'S079': '24518',
 'S080': '69632',
 'S081': '2848',
 'S082': '25591',
 'S083': '9053',
 'S084': '16084',
 'S086': '3478',
 'S089': '73415',
 'S091': '20125',
 'S092': '11393',
 'S094': '29796',
 'S098': '96545',
 'S101': '44',
 'S103': '222',
 'S104': '775',
 'S106': '33417',
 'S107': '2809',
 'S109': '1044',
 'S112': '1056',
 'S113': '2283',
 'S114': '1193',
 'S115': '2134',
 'S116': '57068',
 'S120': '781',
 'S121': '8327',
 'S122': '17600',
 'S123': '104',
 'S125': '4196',
 'S126': '12020',
 'S127': '6394',
 'S128': '1164',
 'S129': '14037',
 'S130': '521',
 'S131': '991',
 'S134': '29796',
 'S135': '781',
 'S136': '781',
 'S137': '96545'}

## Analyze

In [5]:
sources = set(df_sample100_samples['original_track_id'].str.strip())
receivers = set(df_sample100_samples['sample_track_id'].str.strip())
both = sources & receivers
print(both)

set()

In [8]:
# Rows where the pair appears more than once (keeps all occurrences)
dupes = df_sample100_samples[
    df_sample100_samples.duplicated(subset=['original_track_id', 'sample_track_id'], keep=False)
].sort_values(['original_track_id', 'sample_track_id'])
display(dupes)

,sample_id,original_track_id,sample_track_id,t_original,t_sample,n_repetitions,sample_type,interpolation,comments
1,S002,T003,T004,0,0,4,riff,no,intro
2,S003,T003,T004,34,53,3,riff,no,refrain with horns
101,S131,T003,T004,23,20,9,riff,no,repeated beat (of which 3 included in S2)
7,S008,T014,T013,74,5,10,riff,maybe,beginning of riff counted (rest 'chopped')
100,S130,T014,T013,68,0,1,riff,no,intro not interpolated
11,S013,T023,T022,1,10,51,riff,maybe,piano
99,S129,T023,T022,11,84,2,riff,maybe,saxophone
14,S016,T029,T028,0,37,50,riff,no,
98,S128,T029,T028,5,27,4,riff,no,10 sec refrain
15,S017,T031,T030,8,10,43,riff,no,first half of loop
97,S127,T031,T030,46,13,43,riff,no,end of loop
19,S021,T038,T037,0,0,50,riff,no,the guitar bar
96,S126,T038,T037,4,52,10,riff,no,the guitar + brass bar
22,S024,T042,T041,0,4,40,riff,no,the guitar bar
95,S125,T042,T041,7,12,16,riff,no,the guitar + strings bar
26,S029,T052,T051,0,10,85,beat,no,only the measures with single BD counted
94,S124,T052,T051,1,13,80,beat,no,only the measures with double BD counted
34,S038,T062,T063,35,1,5,riff,no,refrain w/ vocals (long)
93,S123,T062,T063,59,49,44,riff,no,verse (very soft)
35,S039,T064,T065,25,22,157,riff,no,the flute verse
91,S121,T064,T065,2,0,12,riff,no,the intro/refrain riff
39,S043,T072,T073,0,5,55,riff,no,piano part
92,S122,T072,T073,4,32,5,riff,no,brass part
77,S094,T167,T166,6,15,43,riff,no,Bass + synth
102,S134,T167,T166,2,25,14,riff,no,Just bass
78,S098,T173,T172,108,5,71,riff,no,
105,S137,T173,T172,1,44,14,riff,no,
90,S120,T199,T184,5,2,71,riff,no,
103,S135,T199,T184,14,58,3,riff,no,brass riff
104,S136,T199,T184,66,0,2,riff,no,brass crescendo

In [10]:
# Why are there duplicates?
edges = dupes[['original_track_id', 'sample_track_id']].drop_duplicates()
len(edges)

14

## CSV

In [ ]:
import csv
from collections import defaultdict

result = defaultdict(list)

with open(path_csv_samples, newline="", encoding='latin-1') as f:
    reader = csv.DictReader(f)
    for row in reader:
        result[row["sample_track_id"]].append(row["original_track_id"])
result = dict(result)

In [ ]:
len(result)

In [ ]:
max([len(v) for v in result.values()])

In [ ]:
result

In [ ]:
df_tracks = pd.read_csv(path_csv_tracks)
display(df_tracks)

In [ ]:
paths_sample100_audio = list(dir_sample100.rglob('*.mp3'))
print(len(paths_sample100_audio))